/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mod_utilisateur (void);
GtkWidget* create_af_utilisateur (void);
GtkWidget* create_aj_utilisateur (void);
GtkWidget* create_recherche (void);
GtkWidget* create_Login (void);
GtkWidget* create_welcome (void);
